# TODO map directory to docker volume and persist

version: "3"
services:
  rdf4j:
    image: eclipse/rdf4j-workbench:amd64-latest
    ports:
      - 8080:8080
  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./docker/plugins:/var/lib/neo4j/plugins
    environment:
      - NEO4J_AUTH=neo4j/admin