/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package meetifai

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class MeetifaiApplication

fun main(args: Array<String>) {
    runApplication<MeetifaiApplication>(*args)
}